Add ability to catch entities with fishing
Archy-X/AuraSkills pull request #301
Opened 2024-07-04 09:23 UTC by ErikSzabo

This PR adds a new entity loot type for fishing (or it can be added to other loot tables as well, it just didn't really make sense).
The caught entity can be a vanilla entity (typically a mob) or a MythicMobs using the `mythicmobs:` prefix. Entity health, damage, and level can also be configured.

The vertical and horizontal velocities are also configurable for fishing but already have default values.

Example configuration in `fishing.yml`:

```yml
type: fishing
pools:
  rare:
    base_chance: 100
    selection_priority: 1
    loot:
      - type: entity
        entity: zombie
        name: "&6My Little Zombie"
        weight: 50
        health: 100
        damage: 100
        velocity:
          horizontal: 1.2
          vertical: 1.3
      - type: entity
        entity: mythicmobs:SkeletonKing
        weight: 50
        level: 10
```

2024-07-04 09:27 UTC, ErikSzabo commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/handler/LootHandler.java
> +        }
This can be dumb if the event is canceled since the entity will spawn and will be removed immediately. Sadly I don't know any other way without using NMS.

2024-07-05 06:56 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntityProperties.java
> +                               Integer level,
These should be primitives not the class versions

2024-07-05 06:57 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntityProperties.java
> +                               Integer level,
Ah nevermind I see you null check them later

2024-07-05 07:09 UTC, Archy-X requested changes
Initial formatting review, will need to test in game personally later.

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/hooks/mythicmobs/loot/MythicEntitySupplier.java
> +public class MythicEntitySupplier extends EntitySupplier {
Add empty line between class definition and constructor

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntityProperties.java
> +                config.node("level").empty() ? null :config.node("level").getInt(),
Ensure space after colon

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntitySupplier.java
> +public abstract class EntitySupplier {
Empty line after

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/EntitySupplier.java
> +    public abstract Entity spawnEntity(AuraSkills plugin, Location location);
Add empty line between methods

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/VanillaEntityParser.java
> +public class VanillaEntityParser implements CustomEntityParser {
Add empty line after

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/handler/LootHandler.java
> +        if(hVelocity == null) hVelocity = 1.2f;
Space after if

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/parser/EntityLootParser.java
> +public class EntityLootParser implements LootParser {
Add empty line

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/type/EntityLoot.java
> +public class EntityLoot extends Loot {
Add empty line

2024-07-05 07:09 UTC, Archy-X commented on bukkit/src/main/java/dev/aurelium/auraskills/bukkit/loot/entity/VanillaEntitySupplier.java
> +            entity.setMetadata("aura_skills_level", new FixedMetadataValue(plugin, getEntityProperties().level()));
auraskills should be one word without an underscore

2024-07-05 07:17 UTC, ErikSzabo commented
Made those changes. Also enabled auto formatting in Intellij on save for the future :'D

2024-07-06 05:15 UTC, Archy-X approved these changes

2024-07-06 06:44 UTC, merged